export const DEFAULT_BUDGET = 100000000;
export const DEFAULT_CARGO_CAPACITY = 650;
export const DEFAULT_TAX = 5;
export const DEFAULT_ROI_PERCENTAGE = 5;
export const DEFAULT_PROFIT_CHECK_INTERVAL = 30;
export const DEFAULT_PROFIT_CHECK_MIN_VALUE = 5000000;
export const MAX_CARGO_CAPACITY = 25775;
export const ILLEGAL_ITEMS = [3721];
